In [1]:
import numpy as np

In [20]:
rows = int(input())

headers = [j for j in input().split(',')]

a = [[int(j) for j in input().split(',')] for i in range(rows)]

3
hello,hello
1,2
2,3
4,5


In [22]:
headers = np.array(headers) 
print(headers)

['hello' 'hello']


In [23]:
a = np.array(a, dtype=np.int32)
print(a)

[[1 2]
 [2 3]
 [4 5]]


In [24]:
array = np.concatenate((headers, a), axis=0)
print(array)

ValueError: all the input arrays must have same number of dimensions

In [17]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [16]:
npa = np.loadtxt('presidents.csv',
                 delimiter=',',
                 skiprows=1,
                 usecols=[0, 2, 3, 4, 5, 6],
                 dtype='int')

npa

array([[   1, 1789, 1797,   57, 1732,  189],
       [   2, 1797, 1801,   61, 1735,  170],
       [   3, 1801, 1809,   57, 1743,  189],
       [   4, 1809, 1817,   57, 1751,  163],
       [   5, 1817, 1825,   58, 1758,  183],
       [   6, 1825, 1829,   57, 1767,  171],
       [   7, 1829, 1837,   61, 1767,  185],
       [   8, 1837, 1841,   54, 1782,  168],
       [   9, 1841, 1841,   68, 1773,  173],
       [  10, 1841, 1845,   51, 1790,  183],
       [  11, 1845, 1849,   49, 1795,  173],
       [  12, 1849, 1850,   64, 1784,  173],
       [  13, 1850, 1853,   50, 1800,  175],
       [  14, 1853, 1857,   48, 1804,  178],
       [  15, 1857, 1861,   65, 1791,  183],
       [  16, 1861, 1865,   52, 1809,  193],
       [  17, 1865, 1869,   56, 1808,  178],
       [  18, 1869, 1877,   46, 1822,  173],
       [  19, 1877, 1881,   54, 1822,  174],
       [  20, 1881, 1881,   49, 1831,  183],
       [  21, 1881, 1885,   50, 1829,  183],
       [  22, 1885, 1889,   47, 1837,  180],
       [  

In [17]:
# What is the mean age at inauguration?
npa[:, 3].mean()

54.63636363636363

In [18]:
# When was the first president inaugurated?
npa[:, 1].min()

1789

In [19]:
#What is the average height of our presidents?
npa[:, 5].mean()

179.75

In [20]:
# Print all heights in inches.
npa[:, 5]*0.393701

array([74.409489, 66.92917 , 74.409489, 64.173263, 72.047283, 67.322871,
       72.834685, 66.141768, 68.110273, 72.047283, 68.110273, 68.110273,
       68.897675, 70.078778, 72.047283, 75.984293, 70.078778, 68.110273,
       68.503974, 72.047283, 72.047283, 70.86618 , 66.141768, 70.86618 ,
       66.92917 , 70.078778, 71.653582, 70.86618 , 72.047283, 70.078778,
       71.653582, 74.015788, 68.897675, 70.472479, 72.047283, 75.984293,
       71.653582, 72.047283, 69.685077, 72.834685, 74.015788, 74.015788,
       71.653582, 72.834685])

In [21]:
# Add a column to the array that contains the term time of each president.

npa = np.insert(npa,
                6,
                npa[:,2] - npa[:,1],
                axis=1)

npa

array([[   1, 1789, 1797,   57, 1732,  189,    8],
       [   2, 1797, 1801,   61, 1735,  170,    4],
       [   3, 1801, 1809,   57, 1743,  189,    8],
       [   4, 1809, 1817,   57, 1751,  163,    8],
       [   5, 1817, 1825,   58, 1758,  183,    8],
       [   6, 1825, 1829,   57, 1767,  171,    4],
       [   7, 1829, 1837,   61, 1767,  185,    8],
       [   8, 1837, 1841,   54, 1782,  168,    4],
       [   9, 1841, 1841,   68, 1773,  173,    0],
       [  10, 1841, 1845,   51, 1790,  183,    4],
       [  11, 1845, 1849,   49, 1795,  173,    4],
       [  12, 1849, 1850,   64, 1784,  173,    1],
       [  13, 1850, 1853,   50, 1800,  175,    3],
       [  14, 1853, 1857,   48, 1804,  178,    4],
       [  15, 1857, 1861,   65, 1791,  183,    4],
       [  16, 1861, 1865,   52, 1809,  193,    4],
       [  17, 1865, 1869,   56, 1808,  178,    4],
       [  18, 1869, 1877,   46, 1822,  173,    8],
       [  19, 1877, 1881,   54, 1822,  174,    4],
       [  20, 1881, 1881,   49,

In [22]:
# Print all presidencies in the 18th and 19th century.
npa[npa[:,1] < 1900]

array([[   1, 1789, 1797,   57, 1732,  189,    8],
       [   2, 1797, 1801,   61, 1735,  170,    4],
       [   3, 1801, 1809,   57, 1743,  189,    8],
       [   4, 1809, 1817,   57, 1751,  163,    8],
       [   5, 1817, 1825,   58, 1758,  183,    8],
       [   6, 1825, 1829,   57, 1767,  171,    4],
       [   7, 1829, 1837,   61, 1767,  185,    8],
       [   8, 1837, 1841,   54, 1782,  168,    4],
       [   9, 1841, 1841,   68, 1773,  173,    0],
       [  10, 1841, 1845,   51, 1790,  183,    4],
       [  11, 1845, 1849,   49, 1795,  173,    4],
       [  12, 1849, 1850,   64, 1784,  173,    1],
       [  13, 1850, 1853,   50, 1800,  175,    3],
       [  14, 1853, 1857,   48, 1804,  178,    4],
       [  15, 1857, 1861,   65, 1791,  183,    4],
       [  16, 1861, 1865,   52, 1809,  193,    4],
       [  17, 1865, 1869,   56, 1808,  178,    4],
       [  18, 1869, 1877,   46, 1822,  173,    8],
       [  19, 1877, 1881,   54, 1822,  174,    4],
       [  20, 1881, 1881,   49,

In [23]:
# What is the average height of presidents in the 18th and 19th century?
npa[npa[:,1] < 1900, 5].mean()

177.52

In [24]:
# Which presidents in the 20th century were below 180cm?

npa[(npa[:,5] < 180) & (npa[:,1] >= 1900) & (npa[:,1] < 2000)]

array([[  26, 1901, 1909,   42, 1858,  178,    8],
       [  30, 1923, 1929,   51, 1872,  178,    6],
       [  33, 1945, 1953,   60, 1884,  175,    8],
       [  34, 1953, 1961,   62, 1890,  179,    8],
       [  39, 1977, 1981,   52, 1924,  177,    4]])

In [25]:
# What is the average term time of presidents below 180cm in the 20th century?

npa[(npa[:,5] < 180) & (npa[:,1] >= 1900) & (npa[:,1] < 2000), 6].mean()

6.8

In [26]:
# In which year was the last president inaugurated who was taller than 74 in.?

npa[npa[:,5] * 0.393701 > 74, 1].max()

1993